# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"

    resolvers :
        default :
            web_path : ~

    filter_sets:
        cache: ~
        article_preview:
            quality: 75
            filters:
                thumbnail: { size: [240, 240], mode: outbound }
        article_detail:
            quality: 90
            filters:
                thumbnail: { size: [480, 480], mode: outbound }
